//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DaleKeeper.rc
//
#define IDC_INGAME_MAX                  3
#define IDC_MAX_POSSIBLE                4
#define IDC_INGAME_MAX2                 5
#define IDC_MAX_POSSIBLE2               6
#define IDC_INGAME_MAX3                 7
#define IDC_MAX_POSSIBLE3               8
#define IDD_ABOUTBOX                    100
#define IDD_DALEKEEPER_FORM             101
#define IDR_MAINFRAME                   128
#define IDR_DALEKETYPE                  129
#define IDD_INSTALLATION_PATH           130
#define IDR_ITEMBROWSER                 130
#define IDD_BROWSE_DIR                  131
#define IDR_SPELLBROWSER                131
#define IDD_OPEN_GAME                   132
#define IDR_CREATUREBROWSER             132
#define IDD_INDEX_RESOURCES             134
#define IDD_ABILITIES                   135
#define IDD_SAVING_THROWS               136
#define IDD_SAVE_GAME                   138
#define IDD_COPY_FILES                  139
#define IDD_PROFICIENCIES               141
#define IDD_RESISTANCES                 142
#define IDD_THIEF_SKILLS                144
#define IDD_CHARACTERISTICS             145
#define IDD_ITEM_BROWSER                147
#define IDD_INVENTORY                   148
#define IDD_QUANTITY                    150
#define IDD_SPELL_BROWSER               151
#define IDD_SPELLS                      152
#define IDD_LIMIT_SPELLS                153
#define IDD_MEMORIZATION                154
#define IDD_ITEMFILTER                  158
#define IDD_PORTRAITS                   159
#define IDD_EXPORTOPTIONS               160
#define IDD_MISC_SETTINGS               161
#define IDD_EXPORTRESOURCE              162
#define IDD_AFFECTS                     163
#define IDD_AFFECT_EDIT                 164
#define IDD_AFFECT_DATA_EDIT            165
#define IDD_SETVALUE                    166
#define IDD_OPEN_CHARACTERFILE          167
#define IDD_SAVECHARACTER               168
#define IDD_GLOBALVARS                  169
#define IDD_EDIT_GLOBAL                 170
#define IDC_HANDCUR                     172
#define IDD_EDITLIST                    173
#define IDD_EDIT_USERLIST               174
#define IDD_NAME_REF                    175
#define IDD_STRING_FINDER               176
#define IDD_APPEARANCE                  177
#define IDD_COLORPICK                   178
#define IDD_CREATURE_BROWSER            179
#define IDD_OPEN_CRE                    180
#define IDD_SAVE_CRE                    181
#define IDD_SPECIAL_ABILITIES           182
#define IDD_CHANGESMADE                 183
#define IDD_SPELLFILTER                 184
#define IDD_CREATUREFILTER              185
#define IDD_STATEFLAGS                  186
#define IDC_VERSION                     1000
#define IDS_ERR_CRE0                    1000
#define IDC_EMAIL                       1001
#define IDS_ERR_CRE1                    1001
#define IDC_WEBSITE                     1002
#define IDC_BROWSE                      1002
#define IDS_ERR_CRE2                    1002
#define IDC_PATH                        1003
#define IDS_ERR_CRE3                    1003
#define IDC_SEARCH                      1004
#define IDS_ERR_CRE4                    1004
#define IDC_PATH_INFO                   1005
#define IDS_ERR_CRE5                    1005
#define IDC_TREE                        1006
#define IDS_ERR_CRE6                    1006
#define IDS_ERR_CRE7                    1007
#define IDC_GAMES                       1008
#define IDS_ERR_CRE8                    1008
#define IDC_PROGRESS                    1009
#define IDS_ERR_CRE9                    1009
#define IDS_ERR_CRE10                   1010
#define IDC_NAME                        1011
#define IDS_ERR_CRE11                   1011
#define IDC_PARTYSCROLL                 1012
#define IDS_ERR_CRE12                   1012
#define IDS_ERR_CRE13                   1013
#define IDC_STR                         1013
#define IDS_ERR_CRE14                   1014
#define IDC_STR_PLUS                    1014
#define IDS_ERR_CRE15                   1015
#define IDC_DEX                         1015
#define IDC_CON                         1016
#define IDS_ERR_CRE16                   1016
#define IDC_INT                         1017
#define IDS_ERR_CRE17                   1017
#define IDC_WIS                         1018
#define IDS_ERR_CRE18                   1018
#define IDC_CHA                         1019
#define IDS_ERR_CRE19                   1019
#define IDC_BASEHP                      1020
#define IDS_ERR_CRE20                   1020
#define IDC_EXP                         1021
#define IDS_ERR_CRE21                   1021
#define IDC_GOLD                        1022
#define IDS_ERR_CRE22                   1022
#define IDC_LORE                        1023
#define IDS_ERR_CRE23                   1023
#define IDC_REPUTATION                  1023
#define IDS_ERR_CRE24                   1024
#define IDC_THAC0                       1024
#define IDS_ERR_CRE25                   1025
#define IDC_BASEAC                      1025
#define IDC_TAB                         1026
#define IDS_ERR_CRE26                   1026
#define IDC_LEVEL1                      1026
#define IDC_SAVE_PARALYZATION           1027
#define IDS_ERR_CRE27                   1027
#define IDC_LEVEL2                      1027
#define IDC_SAVE_WAND                   1028
#define IDC_FILENAME                    1028
#define IDS_ERR_CRE28                   1028
#define IDC_LEVEL3                      1028
#define IDC_SAVE_POLYMORPH              1029
#define IDS_ERR_CRE29                   1029
#define IDC_CURRENTHP                   1029
#define IDC_SAVE_BREATH                 1030
#define IDS_ERR_CRE30                   1030
#define IDC_EXP_FORKILL                 1030
#define IDC_SAVE_SPELLS                 1031
#define IDC_PROF_AXE                    1031
#define IDS_ERR_CRE31                   1031
#define IDC_PROF_BOW                    1032
#define IDC_RES_ACID                    1032
#define IDS_ERR_CRE32                   1032
#define IDC_PROF_CLUB                   1033
#define IDC_RES_COLD                    1033
#define IDC_OPEN_LOCKS                  1033
#define IDS_ERR_CRE33                   1033
#define IDC_PROF_XBOW                   1034
#define IDC_RES_ELECTRICITY             1034
#define IDC_MOVE_SILENTLY               1034
#define IDC_GENDER                      1034
#define IDS_ERR_CRE34                   1034
#define IDC_PROF_DAGGER                 1035
#define IDC_RES_FIRE                    1035
#define IDC_FIND_TRAPS                  1035
#define IDC_RACE                        1035
#define IDC_ITEMLIST                    1035
#define IDC_PROF_FAIL                   1036
#define IDC_RES_CRUSHING                1036
#define IDC_PICK_POCKETS                1036
#define IDC_ALIGNMENT                   1036
#define IDC_ITEM_DESC                   1036
#define IDC_PROF_GREATSWORD             1037
#define IDC_RES_PIERCING                1037
#define IDC_CLASS                       1037
#define IDC_ITEMCOUNT                   1037
#define IDC_HIDEINSHADOWS               1037
#define IDC_RES_SLASHING                1038
#define IDC_MAGE_SPECIALTY              1038
#define IDC_KIT                         1038
#define IDC_SETTRAPS                    1038
#define IDC_PROF_HALBERD                1039
#define IDC_RES_MISSILE                 1039
#define IDC_RACIAL_ENEMY                1039
#define IDC_DETECTILLUSIONS             1039
#define IDC_PROF_HAMMER                 1040
#define IDC_RES_MAGIC                   1040
#define IDC_ENEMYALLY                   1040
#define IDC_PROF_LONGSWORD              1041
#define IDC_RES_MAGICFIRE               1041
#define IDC_PROF_MACE                   1042
#define IDC_RES_MAGICCOLD               1042
#define IDC_PROF_MISSILE                1043
#define IDC_PROF_SHORTSWORD             1044
#define IDC_PROF_SPEAR                  1045
#define IDC_PROF_STAFF                  1046
#define IDC_INVENTORY                   1046
#define IDC_CLEAR                       1047
#define IDC_SETQTY                      1048
#define IDC_CHANGEITEM                  1049
#define IDC_ITEMNAME                    1049
#define IDC_QTY                         1050
#define IDC_SETALLQTY                   1050
#define IDC_IDALL                       1051
#define IDC_QTY2                        1051
#define IDC_ASSIGNITEM                  1052
#define IDC_QTY3                        1052
#define IDC_SPELL_DESC                  1053
#define IDC_ASSIGNSPELL                 1054
#define IDC_SPELLLIST                   1055
#define IDC_SPELLCOUNT                  1056
#define IDC_SPELL_LIST                  1057
#define IDC_CHANGESPELL                 1060
#define IDC_CLEAR_SPELL                 1061
#define IDC_MEM_DEC                     1062
#define IDC_MEM_INC                     1063
#define IDC_KNOWNLIMIT                  1063
#define IDC_USE_KNOWNLIMIT              1064
#define IDC_KIT_INNATES                 1064
#define IDC_MEMLIMIT                    1065
#define IDC_USE_MEMLIMIT                1066
#define IDC_MEMONSAVE                   1067
#define IDC_LIST                        1068
#define IDC_MAXINC                      1069
#define IDC_MAXDEC                      1070
#define IDC_ATTACKS                     1075
#define IDC_APPEARANCE                  1077
#define IDC_FILTERITEMS                 1078
#define IDC_COUNTPROMPT                 1079
#define IDC_MULTIPLAYER                 1080
#define IDC_EXPORTITEMS                 1080
#define IDC_DISABLE_SPELL_ICONS         1081
#define IDC_EXPORTITEMRES               1081
#define IDC_VIEWARMOR                   1082
#define IDC_VIEWARROWS                  1083
#define IDC_VIEWAXES                    1084
#define IDC_VIEWBELT                    1085
#define IDC_VIEWBOLTS                   1086
#define IDC_VIEWBOOKS                   1087
#define IDC_VIEWBOOTS                   1088
#define IDC_VIEWBOWS                    1089
#define IDC_VIEWBULLETS                 1090
#define IDC_VIEWCLOAKS                  1091
#define IDC_DESEL_ALL                   1092
#define IDC_SEL_ALL                     1093
#define IDC_VIEWCONTAINERS              1094
#define IDC_VIEWCROSSBOWS               1095
#define IDC_VIEWDAGGERS                 1096
#define IDC_VIEWDARTS                   1097
#define IDC_VIEWFAMILIARS               1098
#define IDC_VIEWFLAILS                  1099
#define IDC_VIEWFOOD                    1100
#define IDC_VIEWGEMS                    1101
#define IDC_VIEWGLOVES                  1102
#define IDC_VIEWHALBERDS                1103
#define IDC_VIEWHAMMERS                 1104
#define IDC_VIEWHANDTOHAND              1105
#define IDC_VIEWHELMS                   1106
#define IDC_VIEWKEYS                    1107
#define IDC_VIEWMACES                   1108
#define IDC_VIEWMISC                    1109
#define IDC_VIEWMORNINGSTARS            1110
#define IDC_VIEWNECKLACES               1111
#define IDC_VIEWPOTIONS                 1112
#define IDC_VIEWRINGS                   1113
#define IDC_VIEWSCROLLS                 1114
#define IDC_VIEWSHIELDS                 1115
#define IDC_VIEWSHORTSWORDS             1116
#define IDC_VIEWSLINGS                  1117
#define IDC_VIEWSPEARS                  1118
#define IDC_VIEWSTAVES                  1119
#define IDC_VIEWSWORDS                  1120
#define IDC_VIEWWANDS                   1121
#define IDC_PROFS                       1122
#define IDC_1STCLASSINC                 1123
#define IDC_1STCLASSDEC                 1124
#define IDC_2NDCLASSINC                 1125
#define IDC_2NDCLASSDEC                 1126
#define IDC_FIRSTCLASSLEVEL_PROMPT      1128
#define IDC_MOVEMENTSPEED               1129
#define IDC_PORTRAIT                    1130
#define IDC_LARGE_PORTRAITS             1132
#define IDC_EXTRACT_LARGE               1133
#define IDC_SMALL_PORTRAITS             1134
#define IDC_EXTRACT_SMALL               1135
#define IDC_EXPORTSPELLS                1138
#define IDC_EXPORTSPELLRES              1139
#define IDC_INCLUDE_DESC                1140
#define IDC_FILTERSPELLS                1140
#define IDC_USE_GRIDLINES               1141
#define IDC_HEALONSAVE                  1142
#define IDC_DEFAULTSINGLE               1143
#define IDC_AFF_DUPLICATE               1144
#define IDC_AFF_REMOVE                  1145
#define IDC_AFF_EDIT                    1146
#define IDC_AFF_TARGET                  1146
#define IDC_AFF_COPY                    1147
#define IDC_AFF_PARAM1                  1147
#define IDC_AFF_PASTE                   1148
#define IDC_AFF_PARAM2                  1148
#define IDC_AFF_FLAGS                   1149
#define IDC_AFF_TIME                    1150
#define IDC_AFF_PROBABILITY             1151
#define IDC_AFF_RESOURCE0               1152
#define IDC_AFF_RESOURCE1               1153
#define IDC_AFF_RESOURCE2               1154
#define IDC_AFF_RESOURCE3               1155
#define IDC_AFF_TYPE                    1157
#define IDC_DATATYPE                    1158
#define IDC_VALUE                       1159
#define IDC_SPELLPROMPT                 1160
#define IDC_SETVALUE_GENDER             1161
#define IDC_SETVALUE_RACE               1162
#define IDC_SETVALUE_ALIGNMENT          1163
#define IDC_COMBO                       1163
#define IDC_SETVALUE_CLASS              1164
#define IDC_SETVALUE_KIT                1165
#define IDC_SETVALUE_ENEMY              1166
#define IDC_CHR_FILENAME                1166
#define IDC_SETVALUE_APPEARANCE         1167
#define IDC_VAR_ADD                     1167
#define IDC_SETVALUE_ENEMYALLY          1167
#define IDC_VAR_EDIT                    1168
#define IDC_VAR_DELETE                  1169
#define IDC_VAR_NAME                    1170
#define IDC_VAR_VALUE                   1171
#define IDC_HACKING                     1171
#define IDC_ZLIB                        1172
#define IDC_MAILTO                      1173
#define IDC_VISIT                       1174
#define IDC_ADDLISTITEM                 1176
#define IDC_EDITLISTITEM                1177
#define IDC_DISPLAYTEXT                 1177
#define IDC_DELETELISTITEM              1178
#define IDC_RANGE                       1179
#define IDC_NAME_REF                    1180
#define IDC_SHORT_REF                   1182
#define IDC_CLEAR_SHORT                 1183
#define IDC_FIND_SHORT                  1184
#define IDC_LONG_REF                    1185
#define IDC_CLEAR_LONG                  1186
#define IDC_FIND_LONG                   1187
#define IDC_SHORT_TEXT                  1188
#define IDC_LONG_TEXT                   1189
#define IDC_STRINGS                     1189
#define IDC_MAX_LENGTH                  1190
#define IDC_TEXT_MATCH                  1191
#define IDC_FIND_STRINGS                1192
#define IDC_NUM_FOUND                   1193
#define IDC_ALPHANUM                    1194
#define IDC_COLOR_LIST                  1196
#define IDC_CREATURE_LIST               1197
#define IDC_EDIT_CREATURE               1198
#define IDC_CREATURE_PROMPT             1199
#define IDC_CREATURE_COUNT              1200
#define IDC_CRE_LIST                    1201
#define IDC_SAVE_MSG                    1202
#define IDC_CRE_FILENAME                1203
#define IDC_EXTRACT_CREATURE            1204
#define IDC_EXTRACTCRE_AS               1205
#define IDC_REFRESH_CRE                 1206
#define IDC_DELETE_CRE                  1207
#define IDC_FILTER_CREATURES            1208
#define IDC_IGNORE_DATA_VERSIONS        1209
#define IDC_KITTYPE                     1210
#define IDC_FROMLEVEL                   1211
#define IDC_TOLEVEL                     1212
#define IDC_REMOVE_KIT                  1213
#define IDC_CHANGELIST                  1215
#define IDC_SEARCHTEXT                  1216
#define IDC_MATCH_CASE                  1217
#define IDC_MATCH_ITEMNAME              1220
#define IDC_MATCH_DESCRIPTION           1221
#define IDC_MATCH_SPELLNAME             1223
#define IDC_CREATURENAME                1226
#define IDC_ENABLE_QUICKSAVES           1228
#define IDS_ERR_GAM0                    1500
#define IDS_ERR_GAM1                    1501
#define IDS_ERR_GAM2                    1502
#define IDS_ERR_GAM3                    1503
#define IDS_ERR_GAM4                    1504
#define IDS_ERR_GAM5                    1505
#define IDS_ERR_GAM6                    1506
#define IDS_ERR_GAM7                    1507
#define IDS_ERR_GAM8                    1508
#define IDS_ERR_GAM9                    1509
#define IDS_ERR_GAM10                   1510
#define IDS_ERR_GAM11                   1511
#define IDS_ERR_GAM12                   1512
#define IDS_ERR_GAM13                   1513
#define IDS_ERR_GAM14                   1514
#define IDS_ERR_GAM15                   1515
#define IDS_ERR_GAM16                   1516
#define IDS_ERR_GAM17                   1517
#define IDS_ERR_GAM18                   1518
#define IDS_ERR_GAM19                   1519
#define IDS_ERR_GAM20                   1520
#define IDS_ERR_GAM21                   1521
#define IDS_ERR_GAM22                   1522
#define IDS_ERR_GAM23                   1523
#define IDS_ERR_GAM24                   1524
#define IDS_ERR_GAM25                   1525
#define IDS_ERR_CHR0                    2000
#define IDS_ERR_CHR1                    2001
#define IDS_ERR_CHR2                    2002
#define IDS_ERR_CHR3                    2003
#define IDS_ERR_CHR4                    2004
#define IDS_ERR_CHR5                    2005
#define IDS_ERR_CHR6                    2006
#define IDS_ERR_MEMMISMATCH             2500
#define ID_SETTINGS_INSTALLATIONDIRECTORY 32771
#define ID_OPENCHAR                     32772
#define ID_FILE_OPENSAVEDGAME           32773
#define ID_CHARACTER_NEXT               32774
#define ID_CHARACTER_PREV               32775
#define ID_PAGE_NEXT                    32776
#define ID_PAGE_PREV                    32777
#define ID_PAGE_ABILITIES               32778
#define ID_PAGE_SAVES                   32779
#define ID_PAGE_PROF                    32780
#define ID_PAGE_RESISTANCES             32781
#define ID_PAGE_THIEF                   32782
#define ID_PAGE_CHARACTERISTICS         32783
#define ID_VIEW_ITEMBROWSER             32784
#define ID_VIEW_INVENTORY               -32750
#define ID_HELP_VISITTHEWEBSITE         32789
#define ID_HELP_SENDEMAILTOAARON        32790
#define ID_VIEW_SPELLBROWSER            32791
#define ID_SETTINGS_SPELLLIMITS         32793
#define ID_SETTINGS_HEALPARTYONSAVE     32794
#define ID_SETTINGS_OPENDEFAULTSINGLEPLAYER 32795
#define ID_TOOLS_EDITOUTOFPARTYCHARACTERS 32796
#define ID_SETTINGS_MISCELLANEOUS       32797
#define ID_HELP_VIEWREADMEDOC           32798
#define ID_FILE_OPENCHARACTERFILE       32799
#define ID_SETTINGS_LISTS_KITS          32802
#define ID_SETTINGS_LISTS_GENDER        32803
#define ID_SETTINGS_LISTS_RACE          32804
#define ID_SETTINGS_LISTS_CLASS         32805
#define ID_SETTINGS_LISTS_ALIGNMENT     32806
#define ID_SETTINGS_LISTS_RACIALENEMY   32807
#define ID_SETTINGS_LISTS_NUMBEROFATACKS 32808
#define ID_SETTINGS_LISTS_PROFICIENCIES 32809
#define ID_VIEW_CREATUREBROWSER         32810
#define ID_FILE_OPENCREFILE             32812
#define ID_SETTINGS_SAVEOVERWRITE_ALLOWONCHRFILES 32813
#define ID_SETTINGS_SAVEOVERWRITE_ALLOWONCREFILES 32814
#define ID_TOOLS_CONVERTTOCRE           32816
#define ID_TOOLS_SPELLMEMORIZATIONCHECK 32817
#define ID_SETTINGS_LISTS_AFFECTS       32818

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         1229
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
